name: OIDC Debug

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Print OIDC Claims
        shell: bash
        run: |
          TOKEN=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
            | jq -r '.value')

          PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f2)

          PAYLOAD="${PAYLOAD}=="

          echo "$PAYLOAD" | base64 -d > claims.json || true

          cat claims.json