name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Debug GitHub Context
        run: |
          echo "Repository: ${{github.Repository}}"
          echo "Ref: ${{ github.ref }}"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::600294641908:role/GitHubTerraformRole
          aws-region: ap-south-1

      - run: terraform init
        working-directory: terraform/verified-access

      - run: terraform apply -auto-approve
        working-directory: terraform/verified-access