name: Terraform Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Debug GitHub Context
        run: |
          echo "Repository: ${{github.Repository}}"
          echo "Ref: ${{ github.ref }}"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::600294641908:role/GitHubTerraformRole
          aws-region: ap-south-1
          
      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - run: terraform init
        working-directory: terraform/verified-access

      - name: Verify Terraform Variables
        run: |
          echo "VPC_ID=${TF_VAR_vpc_id:+SET}"
          echo "APP_SG_ID=${TF_VAR_demo_app_security_group_id:+SET}"
          echo "APP_ENI_ID=${TF_VAR_demo_app_network_interface_id:+SET}"
          echo "OIDC_CLIENT_ID=${TF_VAR_oidc_client_id:+SET}"
          echo "OIDC_CLIENT_SECRET=${TF_VAR_oidc_client_secret:+SET}"
          echo "OIDC_ISSUER=${TF_VAR_oidc_issuer:+SET}"
        working-directory: terraform/verified-access
        env:
          TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
          TF_VAR_demo_app_security_group_id: ${{ secrets.APP_SG_ID }}
          TF_VAR_demo_app_network_interface_id: ${{ secrets.APP_ENI_ID }}
          TF_VAR_oidc_client_id: ${{ secrets.OIDC_CLIENT_ID }}
          TF_VAR_oidc_client_secret: ${{ secrets.OIDC_CLIENT_SECRET }}
          TF_VAR_oidc_issuer: ${{ secrets.OIDC_ISSUER }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -lock-timeout=10m
        working-directory: terraform/verified-access
        env:
          TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
          TF_VAR_demo_app_security_group_id: ${{ secrets.APP_SG_ID }}
          TF_VAR_demo_app_network_interface_id: ${{ secrets.APP_ENI_ID }}
          TF_VAR_oidc_client_id: ${{ secrets.OIDC_CLIENT_ID }}
          TF_VAR_oidc_client_secret: ${{ secrets.OIDC_CLIENT_SECRET }}
          TF_VAR_oidc_issuer: ${{ secrets.OIDC_ISSUER }}
      
