name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Debug GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
      
      - name: Print GitHub Context
        run: |
          echo "Repository=${{ github.repository }}"
          echo "Ref=${{ github.ref }}"
          echo "Event=${{ github.event_name }}"
          echo "Actor=${{ github.actor }}"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::600294641908:role/GitHubTerraformRole
          aws-region: ap-south-1

      - run: terraform init
        working-directory: terraform/containerized-workload

      - run: terraform apply -auto-approve
        working-directory: terraform/containerized-workload